image: node:latest

cache:
  paths:
  - node_modules/

job:
  script:
  - apt-get update -qy
  - apt-get install -y ruby ruby-dev rubygems-integration
  - npm install
  - gem install --no-rdoc --no-ri dpl
  - dpl --provider=heroku --app=spacediscord-anime-bot --api-key=1a86dabd-a90b-4431-b799-6e7fdd41bae6
# change app name and api key if necessary
